name: sax
channels:
  - conda-forge
  - fastai
dependencies:
  # required
  - python>=3.8
  - black
  - fastcore
  - h5py
  - natsort
  - networkx
  - numpy
  - orjson
  - pydantic<2
  - pyyaml
  - pytables
  - tqdm

  # full (recommended)
  - bokeh
  - gdsfactory>=5.33.11
  - graphviz
  - ipykernel
  - ipympl
  - ipywidgets
  - jupyterlab
  - matplotlib
# - pymeep=\*=mpi_mpich_\*
  - pandas
  - pydot
  - scipy
  - shapely

  # dev
  - build
  - bump2version
  - isort
  - jupyter-book
  - make
  - nbdev<2
  - nbstripout
  - papermill
  - patch
  - pip
  - pre-commit
  - pyright
  - pytest
  - pytest-cov
  - pytest-xdist
# - suitesparse # not supported on windows
  - twine

  - pip:
    # jax dependency
    - jax
    - flax
    - jaxlib
#   - klujax # not suppored on windows
    # other
    - tmm
    - sax==0.8.3
