name: sax
channels:
  - conda-forge
  - fastai
dependencies:
  - make==4.3
  - patch==2.7.6
  - suitesparse==5.10.1
  - python==3.9
  - pip==22.0.2
  - black==22.1.0
  - bokeh==2.4.2
  - build==0.7.0
  - bump2version==1.0.1
  - fastcore==1.3.27
  - h5py==3.6.0
  - ipykernel==6.7.0
  - ipympl==0.8.7
  - ipywidgets==7.6.5
  - jupyterlab==3.2.8
  - matplotlib==3.5.1
  - natsort==8.1.0
  - nbdev==1.1.23
  - nbstripout==0.5.0
  - networkx==2.6.3
  - numpy==1.22.1
  - pandas==1.4.0
  - papermill==2.3.4
  - pre-commit==2.17.0
  - pyright==0.0.13
  - pytables==3.7.0
  - pytest==6.2.5
  - pyyaml==6.0
  - scipy==1.7.3
  - shapely==1.8.0
  - tqdm==4.62.3
  - twine==3.7.1
  - pip:
    - flax==0.4.0
    - jax==0.2.28
    - jaxlib==0.1.76
    - tmm==0.1.8
    - sax==0.6.0
